chrome:
  ip: http://127.0.0.1:4444
  desired: chrome
ff12:
  ip: http://192.168.2.106:4444/wd/hub
  desired: firefox
ff13:
  ip: http://127.0.0.1:4444
  desired: firefox
ie7:
  ip: http://10.10.103.196:4444/wd/hub
  desired: internet_explorer
ie8:
  ip: http://10.10.103.197:4444/wd/hub
  desired: internet_explorer
ie9:
  ip: http://10.10.103.219:4444/wd/hub
  desired: internet_explorer
